// © 2026 Giorgio La Malfa. Licenza EUPL-1.2 (LICENZA.md).
// Tutte le stringhe dell'interfaccia, raccolte in un unico punto.
// Nessun testo mostrato all'utente va scritto altrove nel codice.

export const T = {
  nomeApp: 'Oscuramento dei dati personali nei PDF',
  autore: 'Giorgio La Malfa',
  nomeBreve: 'Oscuramento atti',
  sottotitolo:
    'Per atti da pubblicare e documenti da inviare: trova e copre codici fiscali, IBAN, nomi, recapiti e documenti d\u2019identità, e spiega perché.',

  // Testi di rassicurazione (specifica, § 6). Solo affermazioni verificabili.
  // Testi di rassicurazione (specifica, § 6). Solo affermazioni verificabili.
  rassicurazione: {
    locale: 'Il file non lascia il tuo computer: tutto avviene nel tuo browser, senza caricamenti, registrazioni o statistiche. Lo strumento propone e documenta; la decisione resta tua.',
  },

  passi: [
    { numero: 1, titolo: 'Carica', descrizione: 'Scegli il PDF e a cosa serve' },
    { numero: 2, titolo: 'Controlla e scarica', descrizione: 'Guarda le eccezioni, conferma, scarica' },
  ],

  componenti: {
    titolo: 'Componenti di riconoscimento',
    spiegazione:
      'Per individuare i dati, lo strumento usa un modello di riconoscimento dei nomi di persona e, per le scansioni, un motore di riconoscimento ottico in lingua italiana. I componenti vengono caricati una sola volta e conservati nella cache del browser. Dopo il caricamento non avviene alcuna comunicazione di rete.',
    ner: 'Modello di riconoscimento dei nomi (NER multilingue, eseguito in WebAssembly)',
    ocr: 'Riconoscimento ottico dei caratteri, lingua italiana (Tesseract)',
    pdf: 'Lettura e scrittura dei PDF (pdf.js, pdf-lib)',
    statoVerifica: 'verifica in corso…',
    statoLocale: 'presente in locale',
    statoRemoto: 'non presente in locale',
    statoCaricamento: 'caricamento in corso…',
    statoPronto: 'pronto',
    statoErrore: 'errore di caricamento',
    preparazione: 'Preparazione dei componenti di riconoscimento in corso: potrai scegliere il file fra pochi secondi.',
    preparazioneErrore: 'Un componente di riconoscimento non si è caricato:',
    remotoSpiegazione:
      'Il modello di riconoscimento dei nomi non è presente nella cartella dell’applicazione. Può essere scaricato una sola volta da huggingface.co (circa 135 MB) e conservato nella cache del browser. Il download riguarda solo il modello: nessun documento e nessun dato d’uso viene trasmesso. Fino al tuo consenso non viene effettuata alcuna richiesta.',
    remotoPulsante: 'Scarica il modello da huggingface.co',
    remotoRifiuto: 'Senza il modello, i nomi di persona non vengono riconosciuti automaticamente. Le altre categorie di dati (codici fiscali, IBAN, recapiti, dati sulla salute e simili) vengono comunque individuate. Puoi proseguire lo stesso.',
    proseguiSenzaNer: 'Prosegui senza riconoscimento dei nomi',
    caricamentoDi: 'Caricamento di',
  },

  caricamento: {
    titolo: 'Carica il PDF da trattare',
    trascina: 'Trascina qui il file PDF oppure',
    scegli: 'scegli un file',
    formati: 'PDF (anche da scansione o firmato), immagini JPG e PNG, buste di firma .p7m. Un documento per volta, con i suoi allegati nello stesso file.',
    nonPdf: 'Formato non riconosciuto. Sono ammessi PDF, immagini JPG e PNG e buste di firma .p7m.',
    formatoUfficio: 'I documenti di Word, LibreOffice e simili vanno prima salvati come PDF (in Word: File → Salva con nome → PDF; in LibreOffice: File → Esporta come PDF), poi caricati qui. Il PDF conserva il testo e viene trattato al meglio.',
    p7mSenzaContenuto: 'La busta di firma non contiene il documento (firma separata): carica il PDF originale.',
    p7mNonPdf: 'La busta di firma non contiene un PDF, un\u2019immagine JPG o PNG.',
    immagineNonLetta: 'L\u2019immagine non può essere letta. Sono ammessi file JPG e PNG.',
    avvioAutomatico: 'L\u2019analisi parte da sola appena scegli a che cosa serve il documento.',
    protetto:
      'Il PDF è protetto da password. Lo strumento non tenta di forzarlo: rimuovi la protezione con il software con cui è stato creato e ricarica il file.',
    danneggiato: 'Il file non può essere letto come PDF. Potrebbe essere danneggiato o incompleto.',
    attesaComponenti: 'Attendi il caricamento dei componenti di riconoscimento prima di scegliere il file: l’eventuale download del modello deve precedere il caricamento del documento.',
    attesaGenerazione: 'Attendi il termine della generazione, o interrompila, prima di scegliere un nuovo file.',
    avvia: 'Avvia l’analisi',
    fileScelto: 'File scelto',
    pagine: 'pagine',
    scopoTitolo: 'A che cosa serve il documento trattato?',
    scopoSpiegazione:
      'Una sola scelta per documento. Orienta le proposte sui nominativi e sulle altre segnalazioni: ogni proposta è accompagnata dal motivo e dalla norma, si conferma in blocco e si può cambiare. La decisione resta tua e il rapporto ne dà conto.',
    scopoEnte: 'Ente o ufficio (facoltativo, compare nel rapporto)',
    scopoEnteSegnaposto: 'Es. Comune di …, Settore …',
    scopoObbligatorio: 'Indica a che cosa serve il documento: l\u2019analisi parte subito dopo.',
    scopoFonti: 'Fonti',
  },

  analisi: {
    titolo: 'Analisi del documento',
    fasi: {
      apertura: 'Apertura del documento',
      estrazione: 'Estrazione del testo',
      ocr: 'Riconoscimento ottico',
      immagini: 'Ricerca di firme e immagini',
      regole: 'Applicazione delle regole',
      nomi: 'Riconoscimento dei nomi di persona',
      coerenza: 'Verifica di coerenza fra le occorrenze',
      completata: 'Analisi completata',
      interrotta: 'Analisi interrotta',
    },
    pagina: 'Pagina',
    di: 'di',
    interrompi: 'Interrompi',
    residuoMinuti: 'circa {n} minuti',
    residuoSecondi: 'circa {n} secondi',
    avvisoScansione:
      'Il documento, in tutto o in parte, non contiene testo estraibile: viene sottoposto a riconoscimento ottico. L’operazione richiede più tempo.',
    avvisoRisorse:
      'Documento lungo da scansione: la lettura ottica richiede alcuni minuti (indicativamente due o tre secondi per pagina) e molta memoria. La pagina resta utilizzabile; chiudi le altre schede e non ricaricare durante la lettura.',
    avvisoRisorseProsegui: 'Prosegui con il riconoscimento ottico',
    errore: 'Si è verificato un errore durante l’analisi',
  },

  revisione: {
    titolo: 'Controlla e scarica',
    introduzione:
      'I dati personali trovati sono evidenziati nell\u2019anteprima e verranno coperti nel documento scaricato. Qui sotto vedi solo ciò che merita uno sguardo: i nomi lasciati in chiaro perché la legge lo impone e le pagine da controllare. Se va bene, conferma e scarica.',
    daDecidere: 'dati da decidere',
    tuttiDecisi: 'Tutti i dati sono stati decisi.',
    avvisoScansione:
      'Documento da scansione: il riconoscimento ottico può non leggere tutto. Guarda tutte le pagine dell\u2019anteprima prima di scaricare.',
    qualitaOcr: 'Qualità della lettura',
    filtro: 'Mostra',
    filtroTutti: 'tutti i dati trovati',
    filtroA: 'dati vietati',
    filtroB: 'dati non pertinenti',
    filtroC: 'valutati dal contesto',
    filtroP: 'lasciati in chiaro (istituzionali)',
    filtroM: 'aggiunti a mano',
    nessunRilievo: 'Nessun dato per il filtro scelto.',
    nessunRilievoAssoluto:
      'Nessun dato personale individuato automaticamente. Verifica comunque il documento a schermo: lo strumento assiste, non decide.',
    strumenti: 'Manca qualcosa?',
    selezioneManuale: 'Copri un\u2019area con il mouse',
    selezioneManualeAttiva: 'Traccia un rettangolo sulla pagina sopra il testo da oscurare. Premi Esc per annullare.',
    selezioneManualeSpenta: 'Termina',
    selezioneTesto: 'Oscura un testo scrivendolo',
    selezioneTestoTitolo: 'Oscuramento manuale per testo',
    selezioneTestoSpiegazione: 'Scrivi il testo esatto da oscurare: verranno oscurate tutte le sue occorrenze nel documento. Utile anche senza mouse.',
    selezioneTestoEtichetta: 'Testo da oscurare',
    selezioneTestoNessuno: 'Testo non trovato nel documento.',
    selezioneTestoTrovate: 'occorrenze trovate',
    selezioneArea: 'Oscura un\u2019area per coordinate',
    mostraDettagli: 'Vedi e modifica tutti i dati trovati',
    nascondiDettagli: 'Nascondi l\u2019elenco dei dati',
    opzioniAvanzate: 'Opzioni avanzate: tipo di copertura e risoluzione',
    selezioneAreaTitolo: 'Oscuramento manuale di un\u2019area',
    selezioneAreaSpiegazione: 'Indica la pagina e la posizione dell\u2019area in percentuale della pagina (0 = bordo sinistro o superiore, 100 = bordo destro o inferiore). Utile per firme e immagini, anche senza mouse.',
    selezioneAreaEtichetta: 'Area da oscurare',
    areaSinistra: 'Da sinistra (%)',
    areaAlto: 'Dall\u2019alto (%)',
    areaLarghezza: 'Larghezza (%)',
    areaAltezza: 'Altezza (%)',
    paginaNonResa: 'Anteprima non disponibile per questa pagina: memoria insufficiente. Riduci lo zoom del browser o chiudi altre schede, poi scorri di nuovo.',
    paginaTestoAccessibile: 'Testo della pagina',
    pagina: 'Pagina',
    testoRilevato: 'Testo rilevato',
    fonte: 'Fonte normativa',
    stato: 'Stato',
    conferma: 'Conferma l’oscuramento',
    oscura: 'Oscura',
    mantieni: 'Mantieni in chiaro',
    ripristina: 'Ripristina in chiaro',
    riapplica: 'Applica l’oscuramento',
    tutteOccorrenze: 'Applica a tutte le occorrenze',
    occorrenze: 'occorrenze nel fascicolo',
    rimuovi: 'Rimuovi',
    vaiAllaPagina: 'Vai alla pagina',
    modalitaRilievo: 'Copertura per questo dato',
    modalitaPredefinita: 'predefinita',
    proposto: 'proposta dello strumento, da confermare',
    propostaConfermata: 'proposta dello strumento, confermata',
    confermaProposta: 'Conferma la proposta',
    proposteDaConfermare: 'proposte dello strumento da confermare',
    proposteConfermate: 'Tutte le proposte sono state confermate.',
    confermaProposte: 'Conferma tutte le proposte',
    bloccoEtichetta: 'Decisione in blocco per categoria:',
    bloccoOscura: 'Oscura tutti',
    bloccoMantieni: 'Mantieni tutti in chiaro',
    origine: {
      automatico: 'rilevato automaticamente',
      variante: 'variante di un nominativo rilevato',
      manuale: 'aggiunto manualmente',
    },
    stati: {
      oscura: 'sarà oscurato',
      mantieni: 'resta in chiaro',
      daDecidere: 'da decidere',
      espungi: 'pagina da espungere',
    },
    motivazioneTitolo: 'Motivazione del ripristino',
    motivazioneA:
      'La norma non ammette eccezioni per questa categoria di dati. Il ripristino è ammesso solo se si tratta di un errore di riconoscimento, cioè se il testo non contiene realmente un dato di questa natura. La motivazione viene registrata nel rapporto.',
    motivazioneB:
      'Indica brevemente perché il dato resta in chiaro. La scelta viene registrata nel rapporto di trattamento.',
    motivazioneObbligatoria: 'La motivazione è obbligatoria per questa categoria.',
    motivazioneSegnaposto: 'Es. il testo è la denominazione di un ufficio, non un dato personale',
    manualeTitolo: 'Oscuramento manuale',
    manualeSpiegazione:
      'Indica la categoria del dato selezionato: ogni oscuramento deve essere riconducibile alla sua fonte normativa nel rapporto.',
    manualeCategoria: 'Categoria del dato',
    manualeScegli: 'scegli una categoria',
    manualeNota: 'Nota facoltativa',
    manualeTesto: 'Testo selezionato',
    manualeArea: 'Area senza testo riconosciuto (ad esempio un’immagine o una firma)',
    annulla: 'Annulla',
    salva: 'Salva',
    pagineViste: 'Pagine riviste a schermo',
    prosegui: 'Prosegui alla scelta della modalità',
    bloccatoC: 'Decidi i dati ancora da controllare per proseguire.',
    ricalcolo: 'Aggiornamento dell’anteprima…',
  },

  riepilogo: {
    oscurati: 'dati personali oscurati automaticamente.',
    oscurato: 'dato personale oscurato automaticamente.',
    chiaroTitolo: 'Lasciati in chiaro perché la legge ne impone la pubblicazione',
    chiaroNota: 'Lo strumento lo ha dedotto dal testo. Se non è così, oscura.',
    chiaroTitoloPrivato: 'Lasciati in chiaro',
    chiaroNotaPrivato: 'Dati di società o enti, non personali. Se vuoi, oscura.',
    controllareTitolo: 'Da controllare',
    ripristinatiTitolo: 'Lasciati in chiaro da te',
    istituzionali: 'dati istituzionali lasciati in chiaro (ruoli pubblici, recapiti di uffici e società)',
    istituzionale: 'dato istituzionale lasciato in chiaro (ruolo pubblico, recapito di ufficio o società)',
    nessuno: 'Nessuna eccezione: controlla l\u2019anteprima e scarica.',
    oscura: 'Oscura',
    oscuraPagina: 'Oscura la pagina',
    lascia: 'Lascia com\u2019è',
    pagina: 'pag.',
  },

  modalita: {
    titolo: 'Tipo di copertura',
    introduzione: 'Il tipo di copertura si applica all’intero documento; per un singolo dato puoi sceglierne uno diverso dall’elenco dei dati trovati. Predefinito: [OMISSIS] per le pubblicazioni obbligatorie (è la convenzione degli atti e mantiene leggibile la frase), oscuramento pieno per gli altri usi.',
    pieno: 'Oscuramento pieno',
    pienoDescrizione: 'Rettangolo nero e rimozione effettiva del testo dal livello testuale. Impostazione predefinita.',
    omissis: 'OMISSIS',
    omissisDescrizione: 'Sostituzione con la dicitura [OMISSIS], sobria e conforme alla prassi degli uffici. Il testo originale viene comunque rimosso.',
    pseudonimo: 'Pseudonimizzazione coerente',
    pseudonimoDescrizione:
      'Sostituzione con un’etichetta stabile, [SOGGETTO 1], [SOGGETTO 2], mantenuta identica in tutto il fascicolo, così che il lettore possa seguire i riferimenti senza identificare le persone. I dati non nominativi vengono sostituiti con [OMISSIS].',
    pseudonimoAvvertenza:
      'Le etichette [SOGGETTO n] collegano fra loro tutte le informazioni sulla stessa persona: il documento resta un dato personale (art. 4, n. 5, Regolamento (UE) 2016/679). Nessuna modalità garantisce da sola l’anonimato del documento: dipende da ciò che resta leggibile (considerando 26 del Regolamento).',
    inizialiDomanda: 'Perché non è disponibile la sostituzione con le iniziali?',
    inizialiRisposta:
      'Non basta sostituire nome e cognome con le iniziali: occorre oscurare del tutto il nominativo e le altre informazioni che consentono l’identificazione anche a posteriori. Il Garante per la protezione dei dati personali, nella FAQ n. 12 sulla trasparenza online, ha chiarito che la sostituzione con le iniziali non costituisce anonimizzazione. Per questo lo strumento non la offre in alcuna modalità.',
    risoluzione: 'Risoluzione del documento in uscita',
    risoluzioneDescrizione:
      'Il documento trattato viene ricostruito pagina per pagina come immagine, con un livello testuale invisibile per il testo rimasto in chiaro. Una risoluzione più alta migliora la leggibilità e aumenta il peso del file.',
    risoluzioni: {
      150: '150 punti per pollice, file più leggero',
      200: '200 punti per pollice, consigliata',
      300: '300 punti per pollice, massima leggibilità',
    },
  },

  download: {
    titolo: 'Documento trattato e rapporto',
    scaricoResponsabilita: 'Confermando dichiari di aver controllato l\u2019anteprima e le eccezioni: la decisione su cosa pubblicare o inviare resta tua.',
    avvisoFirma:
      'Il documento prodotto è un file nuovo e non reca più la sottoscrizione digitale dell’originale. Valuta con il tuo ufficio come attestarne la conformità all’atto originale prima della pubblicazione.',
    confermaScansione: 'Confermo di aver guardato tutte le pagine del documento scansionato nell\u2019anteprima.',
    // {viste} e {totale} vengono sostituiti con i conteggi correnti.
    confermaScansioneBloccata: 'Documento da scansione: la casella si attiva dopo che hai guardato tutte le pagine nell\u2019anteprima qui sotto. Pagine guardate: {viste} di {totale}.',
    confermaScansioneVai: 'Vai alla prossima pagina da guardare',
    pagineFineTutte: 'Hai guardato tutte le pagine.',
    pagineFineMancano: 'Non tutte le pagine risultano guardate ({viste} di {totale}).',
    pagineFineTorna: 'Torna alla conferma',
    bloccatoScansionePagine: 'Guarda tutte le pagine nell’anteprima ({viste} di {totale}), poi spunta la conferma.',
    bloccatoScansioneConferma: 'Spunta la conferma della revisione a schermo per scaricare.',
    bloccatoC: 'Decidi prima i dati da controllare.',
    bloccatoProposte: 'Conferma o modifica le proposte per proseguire.',
    genera: 'Confermo e scarico',
    rigenera: 'Genera di nuovo',
    generazione: 'Generazione in corso…',
    generazionePagina: 'Pagina',
    scaricaDocumento: 'Scarica il documento trattato',
    scaricaRapporto: 'Scarica il rapporto di trattamento',
    scaricaImmagine: 'Scarica come immagine (JPG)',
    riepilogo: 'Il documento è pronto',
    oscurati: 'dati oscurati',
    mantenuti: 'dati mantenuti in chiaro',
    espunte: 'pagine espunte',
    nuovo: 'Tratta un nuovo documento',
    nuovoConferma: 'Tutti i dati di questa sessione verranno cancellati. Vuoi procedere?',
    errore: 'Errore nella generazione del documento',
    nota: 'Il rapporto va conservato agli atti insieme al documento trattato: consente all’ufficio di dimostrare come ha operato.',
    suffissoDocumento: '_oscurato',
    suffissoRapporto: '_rapporto-trattamento',
  },

  rapporto: {
    titolo: 'Rapporto di trattamento',
    sottotitolo: 'Oscuramento dei dati personali prima della pubblicazione online',
    dataOra: 'Data e ora del trattamento',
    file: 'File originario',
    pagine: 'Numero di pagine',
    pagineEspunte: 'Pagine espunte',
    modalita: 'Modalità di mascheramento adottata',
    scopo: 'Scopo del trattamento',
    ente: 'Ente o ufficio',
    proposteNota:
      'Per lo scopo indicato lo strumento ha proposto una decisione per i rilievi di fascia C secondo i criteri della base di regole, con il motivo riportato accanto a ciascuno; l\u2019utente ha esaminato le proposte e le ha confermate o modificate come indicato. I rilievi privi di proposta sono stati decisi singolarmente.',
    decisioneProposta: 'proposta dallo strumento, confermata',
    decisioneModificata: 'proposta dallo strumento, modificata dall\u2019utente',
    risoluzione: 'Risoluzione del documento trattato',
    tipoDocumento: 'Tipo di documento',
    nativo: 'PDF con testo nativo',
    scansione: 'PDF acquisito da scansione, testo ottenuto per riconoscimento ottico',
    misto: 'PDF misto: alcune pagine con testo nativo, altre da scansione',
    qualitaOcr: 'Qualità stimata del riconoscimento ottico',
    tabellaTitolo: 'Dati trattati',
    colonne: ['N.', 'Pag. · posizione', 'Tipo di dato', 'Fascia', 'Fonte normativa', 'Esito', 'Modificato'],
    fasciaNota: 'Fasce: A = dato vietato (divieto assoluto di diffusione); B = dato mai pertinente alla pubblicazione, oscurato, ripristinabile; C = valutato dal contesto e dallo scopo; preservato = ruolo pubblico o recapito istituzionale, in chiaro; manuale = aggiunto dall’utente.',
    posizioneNota: 'La posizione indica, in percentuale, la distanza del primo rettangolo dal bordo sinistro e dal bordo superiore della pagina. L\u2019esito riportato è quello effettivo della redazione del documento: un dato mantenuto in chiaro ma coperto da un altro oscuramento, o un\u2019etichetta sostituita da un rettangolo pieno per mancanza di spazio, sono segnalati fra parentesi.',
    si: 'sì',
    no: 'no',
    esitoOscurato: 'oscurato',
    esitoMantenuto: 'in chiaro',
    esitoEspunto: 'pagina espunta',
    esitoManuale: 'oscurato (manuale)',
    modalitaPieno: 'rettangolo pieno',
    modalitaOmissis: 'OMISSIS',
    modalitaPseudonimo: 'pseudonimo',
    fasciaCTitolo: 'Rilievi di fascia C e decisione assunta',
    ripristiniTitolo: 'Ripristini decisi dall’utente e relative motivazioni',
    nessuno: 'Nessuno.',
    decisioneOscura: 'oscurato',
    decisioneMantieni: 'mantenuto in chiaro',
    motivazione: 'Motivazione',
    soggetti: 'Etichette di pseudonimizzazione attribuite',
    soggettiNota:
      'La corrispondenza fra etichette e nominativi non è riportata nel rapporto né conservata altrove: la sola chiave è il documento originale, che resta a chi lo detiene. Il documento trattato con etichette coerenti resta un dato personale ai sensi dell’art. 4, n. 5, del Regolamento (UE) 2016/679, perché le etichette collegano fra loro le informazioni sulla stessa persona.',
    coperturaNota:
      'Le coperture conservano la larghezza del testo originale: la lunghezza del dato oscurato resta deducibile. Nessuna modalità garantisce da sola l’anonimato del documento, che dipende da ciò che resta leggibile (considerando 26 del Regolamento (UE) 2016/679).',
    fontiTitolo: 'Fonti normative e di prassi richiamate',
    fontiNota: 'Per ogni fonte sono riportati i passaggi che sorreggono le regole applicate. I passaggi indicati come "sintesi" non sono riproduzioni letterali e vanno letti sul testo ufficiale all\u2019indirizzo indicato. Lo stato di verifica indica se l\u2019ufficio ha riscontrato il testo vigente.',
    fonteVerificata: 'testo riscontrato dall\u2019ufficio il',
    fonteNonVerificata: 'testo non ancora riscontrato dall\u2019ufficio',
    passaggioSintesi: 'sintesi, non letterale',
    fontiVersione: 'Base delle fonti aggiornata al',
    certezzaTitolo: 'Gradi di certezza del riconoscimento',
    certezzaNota: 'Ogni dato trattato è accompagnato dal grado di certezza con cui è stato individuato. I riconoscimenti formali si fondano su strutture verificabili; quelli contestuali su etichette esplicite; quelli statistici sul modello di riconoscimento dei nomi o su parole chiave, e sono quelli su cui la revisione a schermo dell\u2019amministrazione ha maggior rilievo.',
    regoleFondate: 'Regole fondate su: d.lgs. 33/2013, artt. 7-bis e 26; d.lgs. 196/2003, art. 2-septies; Regolamento (UE) 2016/679, artt. 5 e 9; Linee guida del Garante per la protezione dei dati personali n. 243 del 15 maggio 2014; FAQ del Garante sulla trasparenza online.',
    dichiarazioneTitolo: 'Dichiarazione',
    dichiarazione:
      'Il trattamento è stato eseguito localmente sul dispositivo dell’utente, senza trasmissione del documento o di sue parti a servizi esterni. Lo strumento ha carattere di ausilio: individua e segnala i dati secondo le regole indicate, ma la valutazione e la verifica finale sono rimaste in capo a chi pubblica o invia il documento, che ha rivisto i dati individuati e assunto le decisioni riportate in questo rapporto.',
    generatoCon: 'Rapporto generato con',
    versioneRegole: 'Base di regole aggiornata al',
    strumento: 'Strumento',
    strumentoAutore: 'progettato e sviluppato da',
    pagina: 'Pagina',
  },

  // Le fasce (A, B, C, P, M) restano nel modulo delle regole e nel rapporto;
  // sullo schermo compaiono con parole.
  fasce: {
    A: 'Dato vietato',
    B: 'Dato non pertinente',
    C: 'Valutato dal contesto',
    P: 'Istituzionale',
    M: 'Aggiunto a mano',
  },
  fasceDescrizione: {
    A: 'divieto assoluto di diffusione, oscurato',
    B: 'mai pertinente alla pubblicazione, oscurato, ripristinabile',
    C: 'deciso in base al contesto e allo scopo, con il motivo',
    P: 'ruolo pubblico o recapito di ufficio o società, in chiaro',
    M: 'oscuramento aggiunto dall\u2019utente',
  },

  errori: {
    generico: 'Si è verificato un errore imprevisto.',
    memoria: 'Memoria insufficiente per completare l’operazione. Prova con un documento più breve o chiudi le altre schede.',
    nerNonDisponibile: 'Il riconoscimento dei nomi non è disponibile: i nominativi non sono stati individuati automaticamente.',
    ocrNonDisponibile: 'Il riconoscimento ottico non è disponibile.',
    interrotto: 'Operazione interrotta dall’utente.',
  },

};
