// © 2026 Giorgio La Malfa. Licenza EUPL-1.2 (LICENZA.md).
// Casi della suite di prova. Ogni caso descrive un frammento di atto, i nomi
// che il modello dovrebbe riconoscere e ciò che le regole (regole/regole.js)
// devono produrre. I casi nascono dalle revisioni esterne del codice e dai
// documenti reali provati dall'ufficio; quando una regola cambia, cambia
// anche il caso che la descrive, con la fonte accanto.
//
// Formato: vedi prove/motore.js. Scopo predefinito: pubblica.

export const CASI = [
  { id: 'cropbox-firma', titolo: 'D02: coordinate della firma e della pagina nel CropBox traslato', tecnica: 'cropbox' },
  { id: 'rete-risorse-pdf', titolo: 'D01: risorse PDF pronte prima del documento, nessuna richiesta differita', tecnica: 'rete' },
  { id: 'buste-p7m', titolo: 'D12: buste CAdES (DER, BER, annidate, base64, immagine) e rifiuti deterministici', tecnica: 'p7m' },
  // ------------------------------------------------------------ fascia A
  {
    id: 'salute-con-nominativo',
    titolo: 'Patologia riferita a una persona: fascia A e nominativo segnalato',
    testo: 'Il sig. Luigi Bianchi è affetto da diabete.',
    nomi: ['Luigi Bianchi'],
    attesi: [
      { testo: 'diabete', categoria: 'A1', fascia: 'A', decisione: 'oscura' },
      { testo: 'Luigi Bianchi', categoria: 'C1', decisione: 'oscura' },
    ],
  },
  {
    id: 'salute-dipendente',
    titolo: 'Morbo di Parkinson del dipendente (art. 2-septies, comma 8, d.lgs. 196/2003)',
    testo: 'Il dipendente Giorgio Costa è affetto dal morbo di Parkinson.',
    nomi: ['Giorgio Costa'],
    attesi: [
      { testo: 'Parkinson', categoria: 'A1', decisione: 'oscura' },
      { testo: 'Giorgio Costa', categoria: 'C1' },
    ],
  },
  {
    id: 'salute-sovrapposizioni',
    titolo: 'Due riferimenti sanitari che si accavallano: copertura unica',
    testo: "Il sig. Mario Rossi ha un'invalidità riconosciuta dagli uffici competenti in seguito agli accertamenti svolti e risulta inoltre sieropositivo.",
    nomi: ['Mario Rossi'],
    attesi: [
      { testo: 'invalidità', categoria: 'A1' },
      { testo: 'sieropositivo', categoria: 'A1' },
    ],
  },
  {
    id: 'legge-104-senza-persona',
    titolo: 'Riferimento normativo alla legge 104 senza persona: segnalazione, non oscuramento automatico',
    testo: 'Regolamento per i permessi ai sensi della legge 104/1992.',
    nomi: [],
    nonAttesi: [{ testo: '104', categoria: 'A1' }],
  },
  {
    id: 'giudiziario-con-nominativo',
    titolo: 'Condanna alle spese riferita a una persona (FAQ n. 9)',
    testo: 'Il sig. Mario Rossi è condannato alle spese.',
    nomi: ['Mario Rossi'],
    attesi: [
      { testo: 'condannato', categoria: 'C3', decisione: 'oscura' },
      { testo: 'Mario Rossi', categoria: 'C1', decisione: 'oscura' },
    ],
  },

  // ------------------------------------------------------------ identificativi formali
  {
    id: 'codice-fiscale-valido',
    titolo: 'Codice fiscale con carattere di controllo corretto',
    testo: 'Codice fiscale RSSMRA80A01H501U.',
    nomi: [],
    attesi: [{ testo: 'RSSMRA80A01H501U', categoria: 'B1', esatto: true, decisione: 'oscura' }],
  },
  {
    id: 'codice-fiscale-non-valido',
    titolo: 'Codice fiscale con carattere di controllo errato: non riconosciuto',
    testo: 'Codice fiscale RSSMRA80A01H501X.',
    nomi: [],
    nonAttesi: [{ testo: 'RSSMRA80A01H501X', categoria: 'B1' }],
  },
  {
    id: 'iban-con-parole-seguenti',
    titolo: 'IBAN seguito da parole maiuscole: la copertura si ferma al codice',
    testo: 'IBAN IT60X0542811101000000123456 BANCA INTESA',
    nomi: [],
    attesi: [{ testo: 'IT60X0542811101000000123456', categoria: 'B2', esatto: true }],
    nonAttesi: [{ testo: 'BANCA INTESA' }],
  },
  {
    id: 'iban-minuscolo',
    titolo: 'IBAN scritto in minuscolo',
    testo: 'IBAN: it60x0542811101000000123456',
    nomi: [],
    attesi: [{ testo: 'it60x0542811101000000123456', categoria: 'B2' }],
  },
  {
    id: 'carte-di-pagamento',
    titolo: 'Numeri di carta a 16 e 15 cifre (Luhn), anche raggruppati',
    testo: 'Carta 4111111111111111 e 3782 822463 10005.',
    nomi: [],
    attesi: [
      { testo: '4111111111111111', categoria: 'B2' },
      { testo: '3782 822463 10005', categoria: 'B2' },
    ],
  },
  {
    id: 'partita-iva-ditta-individuale',
    titolo: 'Partita IVA e telefono di una ditta individuale: identificativo e recapito della persona fisica (B1, B3)',
    testo: 'Ditta individuale Anna Russo, partita IVA 01234567897, tel. 0612345678',
    nomi: ['Anna Russo'],
    attesi: [
      { testo: '01234567897', categoria: 'B1', decisione: 'oscura' },
      { testo: '0612345678', categoria: 'B3', decisione: 'oscura' },
      { testo: 'Anna Russo', chiave: 'C1_contraente' },
    ],
  },
  {
    id: 'partita-iva-societa',
    titolo: 'Partita IVA e recapiti di una società: dati non personali, preservati',
    testo: 'Alfa s.r.l., via Roma 1, tel. 0912345678, info@alfa.it, P. IVA 01234567897.',
    nomi: [],
    attesi: [{ testo: '01234567897', chiave: 'C6_societa', decisione: 'mantieni' }],
    nonAttesi: [{ testo: '0912345678' }, { testo: 'info@alfa.it' }],
  },

  // ------------------------------------------------------------ recapiti e dati anagrafici
  {
    id: 'posta-elettronica-personale',
    titolo: 'Casella di posta individuale con trattino basso',
    testo: 'Recapito mario_rossi@example.com',
    nomi: [],
    attesi: [{ testo: 'mario_rossi@example.com', categoria: 'B3', esatto: true }],
  },
  {
    id: 'recapito-in-intestazione',
    titolo: 'Recapito nella testata della pagina: probabile recapito istituzionale, preservato',
    intestazione: true,
    testo: 'Comune di Esempio\nSettore Affari Generali\ntel. 0912345678 – affari.generali@example.org\n\nOggetto: liquidazione',
    nomi: [],
    attesi: [{ testo: 'affari.generali@example.org', categoria: 'P', decisione: 'mantieni' }],
    nonAttesi: [{ testo: '0912345678' }],
  },
  {
    id: 'recapito-personale-in-intestazione',
    titolo: 'Recapito personale nella testata ("residente in" sulla stessa riga): oscurato',
    intestazione: true,
    testo: 'Mario Rossi, residente in via Roma 1, tel. 3331234567\n\nAl Comune di Esempio',
    nomi: ['Mario Rossi'],
    attesi: [{ testo: '3331234567', categoria: 'B3', decisione: 'oscura' }],
  },
  {
    id: 'recapiti-istituzionali',
    titolo: 'Recapiti dell\'ente (FAQ n. 5): restano in chiaro',
    testo: 'Comune di Esempio – Ufficio Tecnico, tel. 0912345678, protocollo@comune.esempio.it, PEC comune.esempio@pec.it',
    nomi: [],
    nonAttesi: [{ testo: '0912345678' }, { testo: 'protocollo@comune.esempio.it' }, { testo: 'comune.esempio@pec.it' }],
  },
  {
    id: 'cellulare',
    titolo: 'Numero di cellulare',
    testo: 'Per informazioni cell. 333 1234567.',
    nomi: [],
    attesi: [{ testo: '333 1234567', categoria: 'B3' }],
  },
  {
    id: 'cellulare-dipendente-ufficio',
    titolo: "Cellulare di un dipendente accanto al nome dell'ufficio: resta un recapito individuale",
    testo: "Il sig. Mario Rossi, dipendente dell'Ufficio Tributi, cell. 3331234567.",
    nomi: ['Mario Rossi'],
    attesi: [{ testo: '3331234567', categoria: 'B3', decisione: 'oscura' }],
  },
  {
    id: 'cellulare-societa',
    titolo: 'Cellulare nel blocco di una società: per prudenza resta oscurato (ripristinabile)',
    testo: 'Alfa s.r.l., via Roma 1, cell. 3331234567, tel. 0912345678.',
    nomi: [],
    attesi: [{ testo: '3331234567', categoria: 'B3', decisione: 'oscura' }],
    nonAttesi: [{ testo: '0912345678' }],
  },
  {
    id: 'telefono-ufficio-nel-testo',
    titolo: "Telefono di un ufficio citato nel corpo dell'atto: preservato",
    testo: 'Per informazioni rivolgersi al Settore Lavori Pubblici, tel. 0912345678, nei giorni di apertura.',
    nomi: [],
    nonAttesi: [{ testo: '0912345678' }],
  },
  {
    id: 'telefono-persona-dopo-ufficio',
    titolo: "Telefono di una persona introdotta dopo il nome dell'ufficio: oscurato",
    testo: 'Settore Lavori Pubblici. Il richiedente sig. Mario Rossi, residente in via Roma 1, tel. 0912345678.',
    nomi: ['Mario Rossi'],
    attesi: [{ testo: '0912345678', categoria: 'B3', decisione: 'oscura' }],
  },
  {
    id: 'dichiarante-modulo',
    titolo: 'Modulo di autocertificazione: dichiarante, nascita, residenza, codice fiscale',
    testo: 'Il/La sottoscritto/a ROSSI MARIO nato/a a PALERMO il 01/01/1980\nresidente in VIA ROMA 1, PALERMO\nC.F. RSSMRA80A01H501U',
    nomi: [],
    attesi: [
      { testo: 'ROSSI MARIO', categoria: 'C1', decisione: 'oscura' },
      { testo: 'PALERMO il 01/01/1980', categoria: 'B5' },
      { testo: 'VIA ROMA 1', categoria: 'B3' },
      { testo: 'RSSMRA80A01H501U', categoria: 'B1' },
    ],
  },
  {
    id: 'data-non-di-nascita',
    titolo: 'Data a inizio riga senza luogo di nascita nella riga precedente: non è data di nascita',
    testo: 'La seduta si svolge\nil 01/06/2026 presso la sede comunale.',
    nomi: [],
    nonAttesi: [{ testo: '01/06/2026', categoria: 'B5' }],
  },
  {
    id: 'stato-civile-nucleo',
    titolo: 'Stato civile e nucleo familiare',
    testo: 'Il richiedente, coniugato, con nucleo familiare di 4 componenti.',
    nomi: [],
    attesi: [{ testo: 'coniugato', categoria: 'B5' }, { testo: 'nucleo familiare', categoria: 'B5' }],
  },

  // ------------------------------------------------------------ documenti di identità
  {
    id: 'documento-numero',
    titolo: 'Estremi di un documento di riconoscimento con numero',
    testo: "Identificato con carta d'identità n. AX1234567 rilasciata dal Comune di Roma.",
    nomi: [],
    attesi: [{ testo: 'AX1234567', categoria: 'B4' }],
  },
  {
    id: 'documento-senza-numero',
    titolo: 'Menzione di un documento senza numero: non è un estremo',
    testo: "Carta d'identità rilasciata dal Comune e allegata.",
    nomi: [],
    nonAttesi: [{ testo: "Carta d'identità", categoria: 'B4' }],
  },
  {
    id: 'elenco-documenti-ammessi',
    titolo: 'Elenco di documenti ammessi: non è una riproduzione (ANAC 1310/2016)',
    testo: "Si ammettono carta d'identità, passaporto o patente di guida.",
    nomi: [],
    nonAttesi: [{ testo: 'passaporto', categoria: 'B4' }, { testo: 'passaporto', categoria: 'B4P' }],
  },
  {
    id: 'rinnovo-passaporto',
    titolo: 'Domanda di rinnovo del passaporto: nessun estremo',
    testo: 'Domanda di rinnovo del passaporto prima della scadenza.',
    nomi: [],
    nonAttesi: [{ testo: 'passaporto', categoria: 'B4' }],
  },
  {
    id: 'pagina-documento-identita',
    titolo: 'Pagina con gli indizi di una carta d\'identità nativa: espunta per intero',
    testo: 'REPUBBLICA ITALIANA\nCOMUNE DI ROMA\nCARTA D\'IDENTITÀ N. AX1234567\nCOGNOME ROSSI\nNOME MARIO\nNATO IL 01/01/1980\nSTATURA 1,80\nCAPELLI CASTANI\nOCCHI MARRONI\nFIRMA DEL TITOLARE\nIMPRONTA DEL DITO',
    nomi: [],
    attesi: [{ testo: '', categoria: 'B4P' }],
  },

  // ------------------------------------------------------------ ruoli e nominativi
  {
    id: 'rup-preservato-controinteressato',
    titolo: 'Responsabile del procedimento preservato; controinteressato oscurato (B7)',
    testo: 'Responsabile del procedimento: Anna Verdi. Controinteressato: Marco Conti.',
    nomi: ['Anna Verdi', 'Marco Conti'],
    attesi: [
      { testo: 'Anna Verdi', categoria: 'P', decisione: 'mantieni' },
      { testo: 'Marco Conti', categoria: 'B7', decisione: 'oscura' },
    ],
  },
  {
    id: 'ruolo-e-verbo',
    titolo: 'Un verbo fra il ruolo e il nome interrompe il legame: il nome non è preservato',
    testo: 'IL DIRIGENTE AUTORIZZA IL sig. Carlo Neri al ritiro degli atti.',
    nomi: ['Carlo Neri'],
    attesi: [{ testo: 'Carlo Neri', categoria: 'C1' }],
    nonAttesi: [{ testo: 'Carlo Neri', categoria: 'P' }],
  },
  {
    id: 'rup-recapiti-istituzionali',
    titolo: 'RUP con casella nominativa su dominio istituzionale e telefono: nome e recapiti in chiaro (Garante, FAQ n. 5)',
    testo: 'Il Responsabile del procedimento: dott. Mario Rossi – mario.rossi@comune.esempio.it – tel. 090 1234567.',
    nomi: ['Mario Rossi'],
    attesi: [
      { testo: 'Mario Rossi', categoria: 'P', decisione: 'mantieni' },
      { testo: 'mario.rossi@comune.esempio.it', categoria: 'P', decisione: 'mantieni' },
      { testo: '090 1234567', categoria: 'P', decisione: 'mantieni' },
    ],
  },
  {
    id: 'rup-recapiti-su-righe',
    titolo: 'RUP e casella nominativa su righe successive',
    testo: 'Responsabile del procedimento\ndott. Mario Rossi\ne-mail: m.rossi@comune.esempio.it',
    nomi: ['Mario Rossi'],
    attesi: [{ testo: 'm.rossi@comune.esempio.it', categoria: 'P', decisione: 'mantieni' }],
  },
  {
    id: 'casella-nominativa-senza-ruolo',
    titolo: 'Casella nominativa su dominio istituzionale senza un ruolo accanto: resta individuale (prudenza)',
    testo: 'Per chiarimenti scrivere a mario.rossi@comune.esempio.it entro il termine.',
    nomi: [],
    attesi: [{ testo: 'mario.rossi@comune.esempio.it', categoria: 'B3', decisione: 'oscura' }],
  },
  {
    id: 'funzionario-certificato',
    titolo: 'Pubblico ufficiale che sottoscrive un certificato (responsabile del servizio, cancelliere): in chiaro anche con rumore OCR',
    testo: 'IL RESPONSABILE DEL SERVIZIO CERTIFICATIVO Spr SAS ( MAZZEO LOREDANA )\nIL CANCELLIERE ESPERTO Dott.ssa Anna Verdi',
    nomi: ['MAZZEO LOREDANA', 'Anna Verdi'],
    attesi: [
      { testo: 'MAZZEO LOREDANA', categoria: 'P', decisione: 'mantieni' },
      { testo: 'Anna Verdi', categoria: 'P', decisione: 'mantieni' },
    ],
  },
  {
    id: 'ruolo-non-nominativo',
    titolo: 'Entità del modello fatta di sole parole comuni ("Responsabile Tecnico"): non è un nominativo né genera varianti',
    testo: 'Direttore / Responsabile Tecnico - BIOTECH HOMELAB S.r.l.\nResponsabile Tecnico Energie Rinnovabili',
    nomi: ['Responsabile Tecnico'],
    nonAttesi: [{ testo: 'Tecnico', categoria: 'C1' }],
  },
  {
    id: 'firme-dirigente-e-rup',
    titolo: 'Blocco di firme su due righe: ogni ruolo trova il suo nome, entrambi in chiaro',
    testo: 'Il Dirigente dott.ssa Anna Verdi\nIl Responsabile del procedimento dott. Mario Rossi',
    nomi: ['Anna Verdi', 'Mario Rossi'],
    attesi: [
      { testo: 'Anna Verdi', categoria: 'P', decisione: 'mantieni' },
      { testo: 'Mario Rossi', categoria: 'P', decisione: 'mantieni' },
    ],
  },
  {
    id: 'nome-poi-ruolo',
    titolo: 'Nome seguito dal ruolo sulla riga successiva (intestazione): in chiaro',
    testo: 'Dott. Mario Rossi\nDirigente del Settore Affari Generali',
    nomi: ['Mario Rossi'],
    attesi: [{ testo: 'Mario Rossi', categoria: 'P', decisione: 'mantieni' }],
  },
  {
    id: 'cognome-condiviso',
    titolo: 'D05: due persone con lo stesso cognome: il cognome isolato o ambiguo non eredita la proposta favorevole',
    testo: 'Il consulente Mario Rossi. Il richiedente Luca Rossi. L. Rossi firma. Rossi conferma.',
    nomi: ['Mario Rossi', 'Luca Rossi'],
    attesi: [
      { testo: 'Mario Rossi', chiave: 'C1_contraente', decisione: 'mantieni' },
      { testo: 'L. Rossi', decisione: 'oscura', esatto: true },
      { testo: 'Rossi', decisione: 'oscura', esatto: true },
    ],
  },
  {
    id: 'soglia-mille-esatti',
    titolo: 'D07: mille euro esatti non superano la soglia (art. 26, comma 2: "superiore a mille euro")',
    testo: 'Contributo al sig. Franco Gallo di euro 1000.',
    nomi: ['Franco Gallo'],
    attesi: [{ testo: 'Franco Gallo', chiave: 'C2_sotto', decisione: 'oscura' }],
  },
  {
    id: 'saldo-contributo',
    titolo: 'D07: "saldo del contributo" non è un corrispettivo contrattuale',
    testo: 'Saldo del contributo al sig. Franco Gallo di euro 500.',
    nomi: ['Franco Gallo'],
    attesi: [{ testo: 'Franco Gallo', chiave: 'C2_sotto', decisione: 'oscura' }],
  },
  {
    id: 'dichiarante-maiuscolo-nato',
    titolo: 'D10: il nominativo in maiuscolo si ferma prima di NATO A',
    testo: 'Il sottoscritto MARIO ROSSI NATO A ROMA IL 01/01/1980',
    nomi: [],
    attesi: [{ testo: 'MARIO ROSSI', categoria: 'C1', esatto: true }],
  },
  {
    id: 'firmato-non-ruolo',
    titolo: 'D10: "Firmato" davanti a un nome non prova un ruolo pubblico',
    testo: 'Firmato Mario Rossi',
    nomi: ['Mario Rossi'],
    attesi: [{ testo: 'Mario Rossi', categoria: 'C1', decisione: 'oscura' }],
  },
  {
    id: 'sovrapposizione-categorie',
    titolo: 'D04: riferimento sanitario esteso che contiene la nascita e sfiora la residenza: ogni dato resta con la sua fonte e la coda dell’indirizzo è coperta',
    testo: 'Il sig. Mario Rossi, nato a Roma il 01/01/1980 affetto da diabete e residente in via Roma 1.',
    nomi: ['Mario Rossi'],
    attesi: [
      { testo: 'diabete', categoria: 'A1' },
      { testo: '01/01/1980', categoria: 'B5' },
      { testo: 'via Roma 1', categoria: 'B3' },
    ],
  },
  {
    id: 'cv-testata-recapiti-personali',
    titolo: 'D06: testata di un curriculum con casella gmail e telefono: la posizione non li rende istituzionali',
    intestazione: true,
    testo: 'Curriculum vitae\nMario Rossi\nmario.rossi@gmail.com\ntel. 0612345678\n\nEsperienze professionali',
    nomi: ['Mario Rossi'],
    attesi: [
      { testo: 'mario.rossi@gmail.com', categoria: 'B3', decisione: 'oscura' },
      { testo: '0612345678', categoria: 'B3', decisione: 'oscura' },
    ],
  },
  {
    id: 'rup-casella-personale',
    titolo: 'D06: la casella personale (gmail) del RUP resta individuale anche accanto al ruolo',
    testo: 'Il Responsabile del procedimento: dott. Mario Rossi – mario.rossi@gmail.com',
    nomi: ['Mario Rossi'],
    attesi: [
      { testo: 'Mario Rossi', categoria: 'P' },
      { testo: 'mario.rossi@gmail.com', categoria: 'B3', decisione: 'oscura' },
    ],
  },
  {
    id: 'dirigente-firmatario',
    titolo: 'Dirigente firmatario: preservato (art. 15 d.lgs. 33/2013, FAQ n. 5)',
    testo: 'Il Responsabile del Settore, dott. Antonio Russo, determina quanto segue.',
    nomi: ['Antonio Russo'],
    attesi: [{ testo: 'Antonio Russo', categoria: 'P', decisione: 'mantieni' }],
  },
  {
    id: 'ruolo-privato',
    titolo: 'Presidente di un\'associazione: ruolo privato, non preserva il nominativo',
    testo: "Il presidente sig. Paolo Verdi dell'associazione presenta istanza.",
    nomi: ['Paolo Verdi'],
    attesi: [{ testo: 'Paolo Verdi', categoria: 'C1' }],
    nonAttesi: [{ testo: 'Paolo Verdi', categoria: 'P' }],
  },
  {
    id: 'testimone',
    titolo: 'Testimone: terzo estraneo, oscuramento automatico (B7)',
    testo: 'Il contraente, sentito il testimone sig. Luca Gallo, presenta la relazione.',
    nomi: ['Luca Gallo'],
    attesi: [{ testo: 'Luca Gallo', categoria: 'B7', decisione: 'oscura' }],
  },
  {
    id: 'minore-e-genitore',
    titolo: 'Minore (B8) e genitore (B7)',
    testo: 'Il minore Luca Bianchi è accompagnato dalla madre Maria Ferri.',
    nomi: ['Luca Bianchi', 'Maria Ferri'],
    attesi: [
      { testo: 'Luca Bianchi', categoria: 'B8', decisione: 'oscura' },
      { testo: 'Maria Ferri', decisione: 'oscura' },
    ],
  },
  {
    id: 'legale-rappresentante-non-contraente',
    titolo: 'Legale rappresentante della società affidataria: non è il contraente, resta nominativo generico (proposta di oscuramento)',
    testo: 'Affidataria Alfa s.r.l., legale rappresentante sig. Paolo Verdi.',
    nomi: ['Paolo Verdi'],
    attesi: [{ testo: 'Paolo Verdi', chiave: 'C1', decisione: 'oscura' }],
  },
  {
    id: 'ditta-individuale-contraente',
    titolo: 'Titolare di ditta individuale affidataria: contraente (art. 37 d.lgs. 33/2013), nominativo pubblicabile',
    testo: 'Affidataria: ditta individuale Anna Russo, con sede in via Verdi 3.',
    nomi: ['Anna Russo'],
    attesi: [{ testo: 'Anna Russo', chiave: 'C1_contraente', decisione: 'mantieni' }],
  },
  {
    id: 'variante-cognome-maiuscolo',
    titolo: 'Cognome isolato dopo il nominativo completo: stessa chiave (variante)',
    testo: 'Il sottoscritto MARIO ROSSI presenta istanza. Successivamente Rossi integra gli atti.',
    nomi: ['MARIO ROSSI'],
    attesi: [
      { testo: 'MARIO ROSSI', categoria: 'C1' },
      { testo: 'Rossi', categoria: 'C1', esatto: true },
    ],
  },
  {
    id: 'variante-cognome-breve',
    titolo: 'Cognome di tre lettere riconosciuto come variante',
    testo: 'Il sig. Marco Foa. Foa firma.',
    nomi: ['Marco Foa'],
    attesi: [{ testo: 'Marco Foa', categoria: 'C1' }, { testo: 'Foa', categoria: 'C1', esatto: true }],
  },
  {
    id: 'ricorso-variante',
    titolo: 'Cognome isolato seguito da riferimento giudiziario',
    testo: 'Il sig. Giulio Ferri. Ferri ha presentato ricorso.',
    nomi: ['Giulio Ferri'],
    attesi: [{ testo: 'Ferri', categoria: 'C1', esatto: true }, { testo: 'ricorso', categoria: 'C3' }],
  },

  // ------------------------------------------------------------ vantaggi economici e corrispettivi
  {
    id: 'contributo-sopra-soglia-trasparenza',
    titolo: 'Contributo superiore a mille euro in Amministrazione trasparente: nominativo pubblicabile (art. 26, comma 2)',
    testo: 'Contributo al sig. Franco Gallo di euro 1500.',
    nomi: ['Franco Gallo'],
    attesi: [{ testo: 'Franco Gallo', chiave: 'C2_sopra', decisione: 'mantieni' }],
  },
  {
    id: 'contributo-sopra-soglia-privato',
    titolo: 'Stesso contributo per un uso diverso dalla pubblicazione obbligatoria: proposta di oscuramento (minimizzazione)',
    scopo: 'privato',
    testo: 'Contributo al sig. Franco Gallo di euro 1500.',
    nomi: ['Franco Gallo'],
    attesi: [{ testo: 'Franco Gallo', chiave: 'C2_sopra', decisione: 'oscura' }],
  },
  {
    id: 'contraente-privato',
    titolo: 'Contraente in un documento da inviare: nessun obbligo di pubblicazione, proposta di oscuramento',
    scopo: 'privato',
    testo: 'Affidataria: ditta individuale Anna Russo, con sede in via Verdi 3.',
    nomi: ['Anna Russo'],
    attesi: [{ testo: 'Anna Russo', chiave: 'C1_contraente', decisione: 'oscura' }],
  },
  {
    id: 'partita-iva-persona-pubblica',
    titolo: 'Partita IVA senza contesto societario né personale: proposta prudenziale di oscuramento anche in pubblicazione obbligatoria (D11)',
    testo: 'Liquidazione a favore di Mario Rossi, P. IVA 01234567897, per la fornitura.',
    nomi: ['Mario Rossi'],
    attesi: [{ testo: '01234567897', chiave: 'C6', decisione: 'oscura' }],
  },
  {
    id: 'partita-iva-persona-privato',
    titolo: 'Stessa partita IVA per un uso privato: proposta di oscuramento',
    scopo: 'privato',
    testo: 'Liquidazione a favore di Mario Rossi, P. IVA 01234567897, per la fornitura.',
    nomi: ['Mario Rossi'],
    attesi: [{ testo: '01234567897', chiave: 'C6', decisione: 'oscura' }],
  },
  {
    id: 'contributo-sotto-soglia',
    titolo: 'Contributo inferiore a mille euro: nominativo non pubblicabile (FAQ n. 15)',
    testo: 'Contributo al sig. Franco Gallo di euro 500.',
    nomi: ['Franco Gallo'],
    attesi: [{ testo: 'Franco Gallo', chiave: 'C2_sotto', decisione: 'oscura' }],
  },
  {
    id: 'contributo-euro-posposto',
    titolo: 'Importo con simbolo € posposto',
    testo: "Alla beneficiaria sig.ra Rita Conti è concesso un contributo di 1500 €.",
    nomi: ['Rita Conti'],
    attesi: [{ testo: 'Rita Conti', chiave: 'C2_sopra' }],
  },
  {
    id: 'contributo-salute',
    titolo: 'Contributo che rivela una condizione di disagio o salute: esclusa la pubblicazione (art. 26, comma 4)',
    testo: 'La sig.ra Anna Verdi percepisce un contributo di euro 1500 per assistenza domiciliare.',
    nomi: ['Anna Verdi'],
    attesi: [{ testo: 'Anna Verdi', chiave: 'C2_salute', decisione: 'oscura' }],
  },
  {
    id: 'compenso-consulente',
    titolo: 'Compenso a un consulente: corrispettivo, non vantaggio economico (art. 15)',
    testo: 'Si liquida al consulente sig. Franco Costa il compenso di euro 500.',
    nomi: ['Franco Costa'],
    attesi: [{ testo: 'Franco Costa', chiave: 'C1_contraente', decisione: 'mantieni' }],
    nonAttesi: [{ testo: 'Franco Costa', categoria: 'C2' }],
  },

  // ------------------------------------------------------------ documento reale (modulo occupazionale)
  {
    id: 'modulo-occupazionale-ditta-individuale',
    titolo: 'Dichiarazione di situazione occupazionale del titolare di ditta individuale: dati anagrafici e recapiti sono della persona fisica',
    testo: 'DICHIARAZIONE SITUAZIONE OCCUPAZIONALE\nIl sottoscritto ROSSI MARIO nato a PALERMO il 01/01/1980\nresidente a PALERMO in VIA ROMA 1\ncodice fiscale RSSMRA80A01H501U\nin qualità di titolare della ditta ALFA SERVIZI di Rossi Mario\ncon sede in VIA LIBERTÀ 10, PALERMO, tel. 0912345678, e-mail info@alfaservizi.it\nP. IVA 01234567897\nDICHIARA',
    nomi: ['ROSSI MARIO', 'Rossi Mario'],
    attesi: [
      { testo: 'ROSSI MARIO', categoria: 'C1', decisione: 'oscura' },
      { testo: '01/01/1980', categoria: 'B5' },
      { testo: 'VIA ROMA 1', categoria: 'B3' },
      { testo: 'RSSMRA80A01H501U', categoria: 'B1' },
      { testo: '0912345678', categoria: 'B3', decisione: 'oscura' },
      { testo: 'info@alfaservizi.it', categoria: 'B3', decisione: 'oscura' },
    ],
  },
  {
    id: 'modulo-occupazionale-societa',
    titolo: 'Stessa dichiarazione resa dal legale rappresentante di una società: i recapiti della società restano in chiaro',
    testo: 'DICHIARAZIONE SITUAZIONE OCCUPAZIONALE\nIl sottoscritto ROSSI MARIO nato a PALERMO il 01/01/1980\nresidente a PALERMO in VIA ROMA 1\ncodice fiscale RSSMRA80A01H501U\nDICHIARA\nin qualità di legale rappresentante della società ALFA SERVIZI s.r.l.\ncon sede legale in VIA LIBERTÀ 10, PALERMO, tel. 0912345678, e-mail info@alfaservizi.it\nP. IVA 01234567897',
    nomi: ['ROSSI MARIO'],
    attesi: [
      { testo: 'ROSSI MARIO', categoria: 'C1', decisione: 'oscura' },
      { testo: 'RSSMRA80A01H501U', categoria: 'B1' },
      { testo: '01234567897', chiave: 'C6_societa', decisione: 'mantieni' },
    ],
    nonAttesi: [{ testo: '0912345678' }, { testo: 'info@alfaservizi.it' }],
  },
];
